### ISSUE TITLE
ECL_PitchController body_fixed_turn_offset issue

### ISSUE THREAD

**Issue by dagar** [PX4/ecl#181]
The ecl pitch controller body fixed turn offset is an additional term added to the rate setpoint. 

https://github.com/PX4/ecl/blob/master/attitude_fw/ecl_pitch_controller.cpp#L153

    float body_fixed_turn_offset = (fabsf((CONSTANTS_ONE_G / airspeed) *
				  		tanf(constrained_roll) * sinf(constrained_roll)));

With large roll angles this term becomes enormous and causes problems like in this recent flight. Note the small pitch setpoint, but full elevator deflection.

![ecl](https://cloud.githubusercontent.com/assets/84712/17576654/f73fa580-5f42-11e6-91f4-1b1f56e988ac.png)

I've scaled the roll, pitch, and pitch setpoints to degrees.

Clearly this should be limited, but to what? Controller roll limit?

**Comment by LorenzMeier** [comment]
I guess that sounds a reasonable start. Or the value it would assume at 30 or 40 degrees roll and lock it there.

**Comment by tumbili** [comment]
@dagar Can you please post the entire log?

**Comment by dagar** [comment]
What about constraining the roll it uses for the offset calculation to +- roll setpoint? Then the offset is based on the planes actual roll, but will never go beyond the roll limits, and will only be active during a commanded turn. I need to think through the inverted logic.

**Comment by mujahid-abdulrahim-p** [comment]
The issue here is that the body_fixed_turn_offset term attempts to compensate for the tilted lift vector and prevent altitude loss at large roll angles.  The term is useful for relatively small angles, but beyond some roll angle, the appropriate response might be to stop trying to maintain altitude and allow the aircraft to recover to a normal operating condition.  Even for aircraft that can fly knife edge, it's unlikely that an aircraft should fly a coordinated turn at bank angles beyond 60 degrees.

dagar's comment about the roll setpoint is appropriate, since this provides some notion of autopilot intention and does not apply a pitch rate feedforward in response to a roll disturbance.
