### ISSUE TITLE
Verify delay accounting for down-sampling of sensor data

### ISSUE THREAD

**Issue by RomanBapst** [PX4/ecl#192]
The baro and the mag measurements have been accounted for an additional delay
which stem from down-sampling techniques of the sensor data (see e.g. https://github.com/PX4/ecl/blob/master/EKF/estimator_interface.cpp#L204). We have to verify if in those two cases any down-sampling is actually happening.

**Comment by priseborough** [comment]
Downsampling occurs inside the sensor for the popular MS5611 baro  - see http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=MS5611-01BA03&DocType=Data+Sheet&DocLang=English with the oversampling ratio user adjustable between 256 and 4096. PX4 uses an OSR of 1024.

The use of oversampling is common with MEMS pressure sensors due to the high noise levels but we cannot guarantee it to be universal so there could be an application where the assumption of an oversampled sensor is not valid. It is however the best assumption we can make.

For the magnetometer the best sampling time assumption to use is less clear. The sensors appear to point sample - see https://media.digikey.com/pdf/Data%20Sheets/Honeywell%20PDFs/HMC5883L.pdf and although there is no downsampling done inside the driver itself, the ekf2 module does downsample to a EKF2_MIN_OBS_DT measurement interval to ab averaged value here: https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_main.cpp#L855-L857

For the HMC5883 family of sensors we are polling the sensor at 150Hz which is within the specification of 160Hz for that sensor. In that case the assumption of oversampling is a reasonable one given that the default param value for EKF2_MIN_OBS_DT is 20 msec (50 Hz) so ov average the downsampling will be 3:1 for that sensor.

However for other sensors this may not be the case, however given the potential differences in sensor internal noise filtering (group delay variation), and the EKF's 8msec fusion time step granularity, this is about as good as we can do for a generic solution. Tuning time delays to minimise RMS innovation sequences are still the required for best performance on new hardware.
