### ISSUE TITLE
Altitude estimate is drifting

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#194]
Here is another <4 min flight where the baro didn't drift at all but the altitude estimate drifted 7 meters.
[Logfile](http://logs.uaventure.com/view/DmABoaBZ8g39aqSvBQpBc7)

**Comment by CarlOlsson** [comment]
This was caused by hardware failure and altitude "drifted" after impact.

**Comment by tumbili** [comment]
@CarlOlsson I think the effect you are seeing is due to the effect that the vehicle hit the ground at the end.
If you look at your baro innovations then they don't showy any long term bias, so I don't think this is a problem.
![baro_vs_lpos](https://cloud.githubusercontent.com/assets/7610489/18778250/c1440eaa-8173-11e6-8928-349b9e7ed9d2.png)

**Comment by tumbili** [comment]
@CarlOlsson What do you mean by hardware failure?

**Comment by CarlOlsson** [comment]
Yes in this case it was a bit difficult to say how much the altitude drifted but what do you think of the log file linked here:
https://github.com/PX4/ecl/issues/44
Why does LPOS_Z drift more than the baro?
