### ISSUE TITLE
CI testing for ECL

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#558]
We need some sort of CI testing for PRs going into ECL in order to prevent introduction of bugs such as https://github.com/PX4/ecl/issues/557 and https://github.com/PX4/ecl/issues/554

As a start maybe we can add some (optional)printfs in functions which does not run continuously. Then for every PR we replay some logfiles and compare the output to what is should be.

@dagar Might have more ideas here

**Comment by dagar** [comment]
Yes definitely! Ideally we'd have a range of different testing, including unit tests in ecl/EKF itself, replay testing, simulation testing, etc. Previously @priseborough mentioned the idea of maintaining a good set of representative logs that we could use for "replay testing". For several of these ideas it's all likely going to come down to log analysis. Can you go through a few painful examples we've hit and think about what could have caught the regression at development time?

I'm not sure if this is known, but when you push a branch to PX4/ecl there's a corresponding test branch created in PX4/Firmware for the sake of CI testing. For example PX4/Firmware `ecl_pr-ekfYawCovReset` was created by PX4Buildbot to test PX4/ecl branch `pr-ekfYawCovReset`. Obviously this only works when a corresponding Firmware side change isn't needed, which is why it isn't directly tied to PX4/ecl checks.

![image](https://user-images.githubusercontent.com/84712/51540679-0b141700-1e25-11e9-993e-8bc8e0f0a11a.png)

Let me know if you'd like to discuss any of this on a call. I think establishing solid testing is badly needed if we want to increase the pace of development without constantly breaking things.

FYI @thomasgubler @LorenzMeier

**Comment by CarlOlsson** [comment]
> Previously @priseborough mentioned the idea of maintaining a good set of representative logs that we could use for "replay testing"

Yeah, this would really nice. Unfortunately the backwards compatibility so far has never been prioritized. But if that would change in the future it would be a great option.

> Can you go through a few painful examples we've hit and think about what could have caught the regression at development time?

Except for [this one](https://github.com/PX4/ecl/issues/548) and the ones already mentioned above I don't remember more right now. 
All of these errors could be identified by only looking at which logic that was executed.

> I'm not sure if this is known, but when you push a branch to PX4/ecl there's a corresponding test branch created in PX4/Firmware for the sake of CI testing.

No I didn't know that, cool!

**Comment by dagar** [comment]
> > Previously @priseborough mentioned the idea of maintaining a good set of representative logs that we could use for "replay testing"
> 
> Yeah, this would be really nice. Unfortunately the backwards compatibility so far has never been prioritized. But if that would change in the future it would be a great option.

I'm not sure backwards compatibility necessary should be prioritized. I would only want to do it if we're prepared to refresh them periodically.


> All of these errors could be identified by only looking at which logic that was executed.

That actually might be key. Are we able to effectively test ecl/EKF from log analysis or do we need to get it structured such that unit testing is viable as well?

**Comment by tstellanova** [comment]
Hey @dagar I’d like to learn how PX4Buildbot configures a test branch for ecl — where can I look for more info?

**Comment by dagar** [comment]
> Hey @dagar I’d like to learn how PX4Buildbot configures a test branch for ecl — where can I look for more info?

It's initiated by Jenkins on the PX4/ecl side creating a PX4/Firmware branch with the ecl submodule changed to the corresponding repo and commit. https://github.com/PX4/ecl/blob/a85d3a43edc4ac4b85ae21159510b9c26f7359e6/Jenkinsfile#L166-L190

Example: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fecl/detail/master/39/pipeline/113

Then PX4/Firmware side Jenkins automatically builds and tests the new ecl branch as if it were any other PX4/Firmware change.

**Comment by bresch** [comment]
We now have a change indicator that replays part of a log and compare the output to allow confident refactoring and we start to have quite a few unit tests to avoid regressions. This is not optimal, but is already much better than before and I think we can close this issue for now.
